const PDFDocument = require('pdfkit');

/**
 * Generate product label as PDF
 * @param {Object} record - Seaweed record data
 * @param {Object} farmerInfo - Farmer information
 * @returns {Promise<Buffer>} - PDF buffer
 */
exports.generateLabel = (record, farmerInfo) => {
  return new Promise((resolve, reject) => {
    try {
      // Create PDF document
      const doc = new PDFDocument({ 
        size: 'A4', 
        margin: 50 
      });
      
      let buffers = [];

      // Collect PDF data
      doc.on('data', buffers.push.bind(buffers));
      
      // When PDF is finished
      doc.on('end', () => {
        let pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Add content to PDF
      
      // Header
      doc.fontSize(24)
         .font('Helvetica-Bold')
         .text('Seaweed Product Label', { align: 'center' });
      
      doc.moveDown(1.5);
      
      // Horizontal line
      doc.moveTo(50, doc.y)
         .lineTo(550, doc.y)
         .stroke();
      
      doc.moveDown();

      // Product Information Section
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text('Product Information');
      
      doc.moveDown(0.5);
      
      doc.fontSize(12)
         .font('Helvetica');
      
      doc.text(`Record ID: ${record.recordId}`, { continued: false });
      doc.text(`Seaweed Type: ${record.seaweedType}`);
      doc.text(`Weight: ${record.weight} kg`);
      doc.text(`Harvest Date: ${new Date(record.harvestDate).toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      })}`);
      doc.text(`Processing Method: ${record.processingMethod}`);
      doc.text(`Quality Grade: ${record.quality}`);
      
      doc.moveDown(1.5);

      // Farmer Information Section
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text('Farmer Information');
      
      doc.moveDown(0.5);
      
      doc.fontSize(12)
         .font('Helvetica');
      
      doc.text(`Name: ${farmerInfo.name}`);
      doc.text(`Contact: ${farmerInfo.phone || 'Not provided'}`);
      doc.text(`Email: ${farmerInfo.email || 'Not provided'}`);
      doc.text(`Address: ${farmerInfo.address || 'Not provided'}`);
      
      if (farmerInfo.location && farmerInfo.location.address) {
        doc.text(`Location: ${farmerInfo.location.address}`);
      }
      
      doc.moveDown(1.5);

      // QR Code Section
      if (record.qrCode) {
        doc.fontSize(16)
           .font('Helvetica-Bold')
           .text('Scan QR Code for Details', { align: 'center' });
        
        doc.moveDown(0.5);
        
        // Convert data URL to buffer
        const qrImage = record.qrCode.split(',')[1];
        const qrBuffer = Buffer.from(qrImage, 'base64');
        
        // Add QR code image
        doc.image(qrBuffer, {
          fit: [150, 150],
          align: 'center',
          valign: 'center'
        });
      }

      doc.moveDown(2);
      
      // Footer
      doc.fontSize(10)
         .font('Helvetica')
         .text('This label was generated by Seaweed Packaging System', {
           align: 'center'
         });
      
      doc.text(`Generated on: ${new Date().toLocaleString()}`, {
        align: 'center'
      });

      // Finalize PDF
      doc.end();
      
    } catch (error) {
      reject(error);
    }
  });
};