import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from '../api/axios';
import { toast } from 'react-toastify';
import './PackingChecklist.css';

const PackingChecklist = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [checklist, setChecklist] = useState(null);
  const [record, setRecord] = useState(null);
  const [loading, setLoading] = useState(true);
  const [tasks, setTasks] = useState([]);

  useEffect(() => {
    fetchChecklistData();
  }, [id]);

  const fetchChecklistData = async () => {
    try {
      // Fetch record details
      const recordResponse = await axios.get(`/seaweed/${id}`);
      if (recordResponse.data.success) {
        setRecord(recordResponse.data.data);
      }

      // Generate checklist
      const checklistResponse = await axios.get(`/seaweed/admin/${id}/packing-checklist`);
      if (checklistResponse.data.success) {
        setChecklist(checklistResponse.data.data);
        setTasks(checklistResponse.data.data.tasks);
      }
    } catch (error) {
      toast.error('Failed to load packing checklist');
      navigate(-1);
    } finally {
      setLoading(false);
    }
  };

  const toggleTask = (taskId) => {
    setTasks(tasks.map(task => 
      task.id === taskId ? { ...task, completed: !task.completed } : task
    ));
  };

  const calculateProgress = () => {
    const completedTasks = tasks.filter(task => task.completed).length;
    return Math.round((completedTasks / tasks.length) * 100);
  };

  const printChecklist = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="loading-container">
        <div className="spinner"></div>
        <p>Loading packing checklist...</p>
      </div>
    );
  }

  if (!checklist || !record) {
    return <div className="error-message">Checklist not found</div>;
  }

  const progress = calculateProgress();
  const allCompleted = progress === 100;

  return (
    <div className="checklist-container">
      <div className="checklist-header no-print">
        <button onClick={() => navigate(-1)} className="btn-back">
          ← Back
        </button>
        <h1>Packing Checklist</h1>
        <button onClick={printChecklist} className="btn-print">
          🖨️ Print
        </button>
      </div>

      <div className="checklist-content">
        {/* Record Information Card */}
        <div className="checklist-card info-card">
          <h2>📦 Product Information</h2>
          <div className="info-grid">
            <div className="info-item">
              <span className="label">Record ID:</span>
              <span className="value">{checklist.recordId}</span>
            </div>
            <div className="info-item">
              <span className="label">Farmer:</span>
              <span className="value">{checklist.farmerName}</span>
            </div>
            <div className="info-item">
              <span className="label">Seaweed Type:</span>
              <span className="value">{checklist.seaweedType}</span>
            </div>
            <div className="info-item">
              <span className="label">Weight:</span>
              <span className="value">{checklist.weight} kg</span>
            </div>
            <div className="info-item">
              <span className="label">Quality:</span>
              <span className="value">{checklist.quality}</span>
            </div>
            <div className="info-item">
              <span className="label">Processing:</span>
              <span className="value">{checklist.processingMethod}</span>
            </div>
            <div className="info-item">
              <span className="label">Harvest Date:</span>
              <span className="value">
                {new Date(checklist.harvestDate).toLocaleDateString()}
              </span>
            </div>
            <div className="info-item">
              <span className="label">Generated By:</span>
              <span className="value">{checklist.generatedBy}</span>
            </div>
          </div>
        </div>

        {/* Progress Card */}
        <div className="checklist-card progress-card no-print">
          <h2>📊 Packing Progress</h2>
          <div className="progress-wrapper">
            <div className="progress-bar-container">
              <div 
                className="progress-bar-fill" 
                style={{ width: `${progress}%` }}
              >
                <span className="progress-text">{progress}%</span>
              </div>
            </div>
            <p className="progress-info">
              {tasks.filter(t => t.completed).length} of {tasks.length} tasks completed
            </p>
          </div>

          {allCompleted && (
            <div className="completion-banner">
              ✅ All tasks completed! Ready for delivery.
            </div>
          )}
        </div>

        {/* Checklist Tasks Card */}
        <div className="checklist-card tasks-card">
          <h2>✓ Packing Tasks</h2>
          <div className="tasks-list">
            {tasks.map((task) => (
              <div 
                key={task.id} 
                className={`task-item ${task.completed ? 'completed' : ''}`}
              >
                <div className="task-checkbox-wrapper">
                  <input
                    type="checkbox"
                    id={`task-${task.id}`}
                    checked={task.completed}
                    onChange={() => toggleTask(task.id)}
                    className="task-checkbox no-print"
                  />
                  <div className="checkbox-print">
                    {task.completed ? '☑' : '☐'}
                  </div>
                </div>
                <label 
                  htmlFor={`task-${task.id}`}
                  className="task-label"
                >
                  <span className="task-number">{task.id}</span>
                  <span className="task-text">{task.task}</span>
                  {task.completed && (
                    <span className="task-completed-badge no-print">✓ Done</span>
                  )}
                </label>
              </div>
            ))}
          </div>
        </div>

        {/* Quality Control Notes Card */}
        <div className="checklist-card notes-card">
          <h2>📝 Quality Control Notes</h2>
          <div className="qc-section">
            <h3>Inspection Points:</h3>
            <ul className="qc-list">
              <li>Check for proper color and texture</li>
              <li>Verify no foreign materials or contamination</li>
              <li>Ensure correct moisture content for processing method</li>
              <li>Confirm packaging materials are clean and intact</li>
              <li>Verify label information is accurate</li>
            </ul>
          </div>

          <div className="qc-section">
            <h3>Storage Requirements:</h3>
            <ul className="qc-list">
              {checklist.processingMethod === 'Fresh' && (
                <>
                  <li>Store at 2-4°C temperature</li>
                  <li>Keep in moisture-controlled environment</li>
                  <li>Use within 48 hours</li>
                </>
              )}
              {checklist.processingMethod === 'Dried' && (
                <>
                  <li>Store in cool, dry place</li>
                  <li>Keep away from direct sunlight</li>
                  <li>Ensure proper ventilation</li>
                </>
              )}
              {checklist.processingMethod === 'Frozen' && (
                <>
                  <li>Maintain -18°C or below</li>
                  <li>Avoid temperature fluctuations</li>
                  <li>Check freezer functionality regularly</li>
                </>
              )}
              {checklist.processingMethod === 'Semi-dried' && (
                <>
                  <li>Store at 10-15°C temperature</li>
                  <li>Monitor humidity levels</li>
                  <li>Rotate stock regularly</li>
                </>
              )}
            </ul>
          </div>

          <div className="signature-section">
            <div className="signature-box">
              <p className="signature-label">Packed By:</p>
              <div className="signature-line"></div>
              <p className="signature-date">Date: _______________</p>
            </div>

            <div className="signature-box">
              <p className="signature-label">Verified By:</p>
              <div className="signature-line"></div>
              <p className="signature-date">Date: _______________</p>
            </div>
          </div>
        </div>

        {/* Generated Info */}
        <div className="checklist-footer">
          <p>Generated on: {new Date(checklist.generatedDate).toLocaleString()}</p>
          <p>Document ID: {checklist.recordId}</p>
        </div>
      </div>
    </div>
  );
};

export default PackingChecklist;